# main menu

[[main]]
name = "About"
weight = 1

[[main]]
name = "Why Incubyte"
url = "https://incubyte.co/why-incubyte"
parent = "About"
weight = 1

[[main]]
name = "Events"
url = "https://www.incubyte.co/events"
parent = "About"
weight = 2


[[main]]
name = "Work"
weight = 2

[[main]]
name = "Product Development"
url = "https://www.incubyte.co/software-development"
parent = "Work"
weight = 1

[[main]]
name = "Software Modernization"
url = "https://www.incubyte.co/enhance-and-modernize"
parent = "Work"
weight = 2

[[main]]
name = "Consulting"
url = "https://www.incubyte.co/consulting"
parent = "Work"
weight = 3

[[main]]
name = "Virtual CTO"
url = "https://www.incubyte.co/virtual-cto"
parent = "Work"
weight = 4

[[main]]
name = "Resources"
weight = 3

[[main]]
name = "Inspiration!"
url = "https://incubyte.co/inspiration"
weight = 1
parent = "Resources"

[[main]]
name = "Blog"
url = "/"
parent = "Resources"
weight = 2

[[main]]
name = "Careers"
url = "https://incubyte.co/careers"
weight = 4


# footer menu left
[[footer_top]]
name = "About Us"
url = "https://www.incubyte.co/about-us"
weight = 1

[[footer_top]]
name = "Services"
url = "https://www.incubyte.co/what-we-do-overview"
weight = 2

[[footer_top]]
name = "Contact Us"
url = "https://www.incubyte.co/contact-us"
weight = 3

[[footer_top]]
name = "Home"
url = "https://incubyte.co/"
weight = 4

[[footer_top]]
name = "Careers"
url = "https://www.incubyte.co/careers"
weight = 5

# footer menu right
[[footer_bottom]]
name = "Privacy Policy"
url = "https://www.incubyte.co/privacy-policy"
weight = 1

[[footer_bottom]]
name = "Terms and Conditions"
url = "https://www.incubyte.co/privacy-policy"
weight = 2

[[footer_bottom]]
name = "Cookie Policy"
url = "https://www.incubyte.co/privacy-policy"
weight = 3
